name: project-doctor
on: [push, pull_request]
jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup venv
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip isort black flake8 mypy pytest pre-commit
      - name: Run doctor (quick)
        run: ./.venv/bin/python dev_doctor.py
      - name: Verify toolchain (optional)
        run: ./.venv/bin/python dev_doctor.py --run-verify
